nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.tools.bomdemo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: 
          - grafana.tools.bomdemo.com
        secretName: mimir-cert