nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.tools.bomdemo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: 
          - grafana.tools.bomdemo.com
        secretName: mimir-cert

serviceAccount:
  # -- Whether to create a service account or not. In case 'create' is false, do set 'name' to an existing service account name.
  create: false
  # -- Override for the generated service account name.
  name: mimir
  annotations: {}


minio:
  enabled: false

mimir:
  structuredConfig:
    alertmanager_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com
    
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com
    ruler_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com

gateway:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: mimir.tools.bomdemo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - mimir.tools.bomdemo.com
        secretName: mimir-cert

metaMonitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
  grafanaAgent:
    enabled: true
    logs:
      enabled: true
      remote:
        url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
    metrics:
      enabled: true


