nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.tools.bomdemo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: 
          - grafana.tools.bomdemo.com
        secretName: mimir-cert

serviceAccount:
  # -- Whether to create a service account or not. In case 'create' is false, do set 'name' to an existing service account name.
  create: false
  # -- Override for the generated service account name.
  name: mimir
  annotations: {}


minio:
  enabled: false

alertmanager:
  statefulSet:
    enabled: false
  persistentVolume:
    # If true will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

compactor:
  persistentVolume:
    # If true will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

ingester:
  statefulSet:
    enabled: false
  persistentVolume:
    # If true will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

store_gateway:
  persistentVolume:
    # If true will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

mimir:
  structuredConfig:
    alertmanager_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com
    
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com
    ruler_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com

