nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.tools.bomdemo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: 
          - grafana.tools.bomdemo.com
        secretName: mimir-cert


mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.us-east-2.amazonaws.com

    blocks_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
    alertmanager_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
    ruler_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822

