nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.tools.bomdemo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts: 
          - grafana.tools.bomdemo.com
        secretName: mimir-cert

minio:
  enabled: false

mimir:
  structuredConfig:
    alertmanager_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com
    ruler_storage:
      s3:
        bucket_name: mimir-bomdemo-dev-0585822
        endpoint: s3.us-east-2.amazonaws.com

