apiVersion: v1
kind: Secret
metadata:
  name: tools-deploy
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/BOM-DEMO/tools-deploy