# https://github.com/kubernetes-sigs/kustomize/issues/4593
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cilium
name: cilium
namespace: kube-system
releaseName: cilium
repo: https://helm.cilium.io/
valuesFile: values.yaml