serviceAccounts:
  cilium:
    create: true
    name: cilium
    annotations: {
      eks.amazonaws.com/role-arn: arn:aws:iam::593393184947:role/cilium-c6175a5
    }

eni:
  enabled: true
ipam:
  mode: eni
egressMasqueradeInterfaces: eth0
tunnel: disabled

hubble:
  ui:
    enabled: true
  relay:
    enabled: true