serviceAccounts:
  cilium:
    create: true
    name: cilium
    annotations: {
      eks.amazonaws.com/role-arn: arn:aws:iam::593393184947:role/cilium-c6175a5
    }

eni:
  enabled: true
ipam:
  mode: eni
egressMasqueradeInterfaces: eth0
tunnel: disabled

hubble:
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
      - "httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
      - "kafka:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_namespace,destination_namespace,traffic_direction"
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
      labels: {
        instance: primary
      }
    dashboards:
      enabled: true
      namespace: monitoring
      label: grafana_dashboard
      labelValue: "1"
  ui:
    enabled: true
    ingress:
      enabled: true
      annotations: {
        kubernetes.io/ingress.class: nginx,
        cert-manager.io/cluster-issuer: letsencrypt
      }
      hosts:
        - hubble.tools.bomdemo.com
      tls:
        - secretName: hubble-cert
          hosts:
            - hubble.tools.bomdemo.com
  relay:
    enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels: {
      instance: primary
    }