apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: argocd-secret
  namespace: doppler-operator-system
  labels:
    abc: def
spec:
  tokenSecret:
    name: argocd-dev-doppler-token-secret
  managedSecret:
    name: argocd-doppler-secret
    namespace: argocd
  nameTransformer: camel