apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki
name: loki-distributed
namespace: monitoring
releaseName: loki
repo: https://grafana.github.io/helm-charts
valuesFile: values.yaml