apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki
name: loki
namespace: monitoring
releaseName: loki
repo: https://grafana.github.io/helm-charts
valuesFile: values.yaml
apiVersions: 
  - monitoring.grafana.com/v1alpha1/MetricsInstance
  - monitoring.coreos.com/v1/ServiceMonitor