#TODO: probably need more than defaults
loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki-bomdemo-dev-8fa1c75
      ruler: loki-bomdemo-dev-8fa1c75
      admin: loki-bomdemo-dev-8fa1c75
    type: s3
    s3:
      region: us-east-2

backend:
  persistence:
    enableStatefulSetAutoDeletePVC: false


minio:
  enabled: false

serviceAccount:
  create: false
  name: loki

monitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: true
    interval: 20s
    metricsInstance:
      enabled: true
      remoteWrite: 
      - http://mimir-nginx.monitoring.svc.cluster.local/prometheus/api/v1/push
  selfMonitoring:
    grafanaAgent:
      installOperator: false

serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: false

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx,
    cert-manager.io/cluster-issuer: letsencrypt
  }
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - loki.tools.bomdemo.com
  
  tls:
    - hosts:
      - loki.tools.bomdemo.com
      secretName: loki-cert