#TODO: probably need more than defaults
loki:
  storage:
    bucketNames:
      chunks: loki-bomdemo-dev-8fa1c75
      ruler: loki-bomdemo-dev-8fa1c75
      admin: loki-bomdemo-dev-8fa1c75
    type: s3
    s3:
      region: us-east-2

backend:
  persistence:
    enableStatefulSetAutoDeletePVC: false


minio:
  enabled: false

serviceAccount:
  create: false
  name: loki

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {
    kubernetes.io/ingress.class: nginx,
    cert-manager.io/cluster-issuer: letsencrypt
  }
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - loki.tools.bomdemo.com
  
  tls:
    - hosts:
      - loki.tools.bomdemo.com
      secretName: loki-cert