# Need to stub out this file in order to add the repo-creds label

apiVersion: v1
kind: Secret
metadata:
  name: argocd-doppler-secret
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
