generators:
- helm-chart.yaml

# policy/v1beta1 was removed in eks 1.25
patchesJson6902:
  - target:
      kind: 'PodDisruptionBudget'
      name: 'ebs-csi-controller'
      version: v1beta1
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: policy/v1 

namespace: kube-system