resources:
  - namespace.yaml
  - ./network-policy.yaml
  - ./agent
  - ./grafana
  - ./loki
  - ./mimir
  - ./tempo

patches:
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/annotations/service.cilium.io~1lb-l7
        value: enabled

namespace: monitoring