resources:
  - namespace.yaml
  - ./network-policy.yaml
  - ./agent
  - ./grafana
  - ./loki
  - ./mimir
  - ./tempo

patches:
  - target:
      kind: Service
    patch: |-
      - op: replace
        path: /metadata/annotations/service.cilium.io~1lb-l7
        value: enabled
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/policy.cilium.io~1proxy-visibility
        value: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/policy.cilium.io~1proxy-visibility
        value: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"
  - target:
      kind: DaemonSet
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/policy.cilium.io~1proxy-visibility
        value: "<Egress/53/UDP/DNS>,<Egress/80/TCP/HTTP>"

namespace: monitoring