ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - grafana.tools.bomdemo.com
  
  # tls:
  #   - hosts:
  #     - grafana.tools.bomdemo.com
  #     secretName: grafana-cert