ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {
    kubernetes.io/ingress.class: nginx,
    cert-manager.io/cluster-issuer: letsencrypt
  }
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - grafana.tools.bomdemo.com
  
  tls:
    - hosts:
      - grafana.tools.bomdemo.com
      secretName: grafana-cert

grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"

# Configure Grafana data sources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      #TODO: Could probably have a way to have data sources configure themselves
    - name: Mimir
      type: prometheus
      url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
      jsonData:
        tlsSkipVerify: true
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        tlsSkipVerify: true
    - name: Tempo
      type: tempo
      url: http://tempo-gateway.monitoring.svc.cluster.local
      jsonData:
        tlsSkipVerify: true