ingress:
  enabled: true
  ingressClassName: nginx
  annotations: {
    nginx.ingress.kubernetes.io/ssl-redirect: "false",
    cert-manager.io/cluster-issuer: letsencrypt
  }
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - grafana.tools.bomdemo.com
  
  tls:
    - hosts:
      - grafana.tools.bomdemo.com
      secretName: grafana-cert