global:
  groundcoverPredefinedTokenSecret:
    # the name of the secret
    secretName: groundcover-doppler-secret
    # the key in the secret containing the token value
    secretKey: GROUNDCOVER_TOKEN

saas:
  tls_skip_verify: true

timescaledb-single:
  persistentVolumes:
    data:
      enabled: false
    wal:
      enabled: false

  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_PASSWORD: password

loki:
  persistence:
    enabled: false

victoria-metrics-single:
  server:
    persistentVolume:
      enabled: false