global:
  groundcover_token: eyJhcGlLZXkiOiJ6REtFZ3NadE5nMjlrdUFUaUZpZVRhWjlKb2Z4S1pBdSIsImlkIjoiZDQ5OGEyZGUtOThjZC00OTE4LThhMzMtM2MwOGNlNGNmMGMxIiwiZW1haWwiOiJicmVudC5ncnViZXI3N0BnbWFpbC5jb20iLCJvcmciOiJicmVudC5ncnViZXI3N0BnbWFpbC5jb20iLCJzZXNzaW9uSWQiOiJjZTljNWZiNy0yYTAxLTRmMWQtYmJiNi1jNWM3ZjRkNDNiNjYifQ==
  # groundcoverPredefinedTokenSecret:
  #   # the name of the secret
  #   secretName: temp-groundcover-secret
  #   # the key in the secret containing the token value
  #   secretKey: GROUNDCOVER_KEY

router:
  # onprem or cloud
  mode: onprem
  enabled: true

timescaledb-single:
  persistentVolumes:
    data:
      enabled: false
    wal:
      enabled: false

  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_PASSWORD: password

loki:
  persistence:
    enabled: false

victoria-metrics-single:
  server:
    persistentVolume:
      enabled: false