global:
  groundcover_token: eyJhcGlLZXkiOiJ6REtFZ3NadE5nMjlrdUFUaUZpZVRhWjlKb2Z4S1pBdSIsImlkIjoiODNiNzI5NzctYjk1MC00MDI4LTgxYjMtZjIxMDAxYzNkZDVhIiwiZW1haWwiOiJicmVudC5ncnViZXI3N0BnbWFpbC5jb20iLCJvcmciOiJicmVudC5ncnViZXI3N0BnbWFpbC5jb20iLCJzZXNzaW9uSWQiOiIyYmYwYmNkNS0zNjA1LTRkMTMtOTU1Ny05YWIxZTIzOGU3MDkifQ==
  # groundcoverPredefinedTokenSecret:
  #   # the name of the secret
  #   secretName: temp-groundcover-secret
  #   # the key in the secret containing the token value
  #   secretKey: GROUNDCOVER_KEY

saas:
  tls_skip_verify: false
  scheme: wss
  host: app.groundcover.com
  port: 443

timescaledb-single:
  persistentVolumes:
    data:
      enabled: false
    wal:
      enabled: false

  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_PASSWORD: password

loki:
  persistence:
    enabled: false

victoria-metrics-single:
  server:
    persistentVolume:
      enabled: false