global:
  groundcover_token: eyJhcGlLZXkiOiJ6REtFZ3NadE5nMjlrdUFUaUZpZVRhWjlKb2Z4S1pBdSIsImlkIjoiYTFiYTIyNjctYzZmOC00MDZiLWIzNjktMjMxYWM5NGM0NDBjIiwiZW1haWwiOiJicmVudC5ncnViZXI3N0BnbWFpbC5jb20iLCJvcmciOiJicmVudC5ncnViZXI3N0BnbWFpbC5jb20iLCJzZXNzaW9uSWQiOiIyYTNhNjg3ZC1jMzcyLTRjNWEtYTAwNC04MDBjZGZmY2Q1MjgifQ==
  # groundcoverPredefinedTokenSecret:
  #   # the name of the secret
  #   secretName: temp-groundcover-secret
  #   # the key in the secret containing the token value
  #   secretKey: GROUNDCOVER_KEY

timescaledb-single:
  persistentVolumes:
    data:
      enabled: false
    wal:
      enabled: false

  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_PASSWORD: password

loki:
  persistence:
    enabled: false

victoria-metrics-single:
  server:
    persistentVolume:
      enabled: false