global:
  groundcoverPredefinedTokenSecret:
    # the name of the secret
    secretName: groundcover-doppler-secret
    # the key in the secret containing the token value
    secretKey: GROUNDCOVER_TOKEN

timescaledb-single:
  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_PASSWORD: password

clusterId: bom-demo-dev

loki:
  persistence:
    storageClassName: aws-gp2