global:
  groundcover_token: eyJhcGlLZXkiOiJlSE4xNTd1TGwyTGxQNXM3ckhKWFRIUWQ0VkpWMTNnTCIsImlkIjoiOTgzYTA4ODEtODk1Zi00MDg0LWFmOGEtOTMxOGJiMzdlNmE1IiwiZW1haWwiOiJtZUBicmVudGdydWJlci5uZXQiLCJvcmciOiJtZUBicmVudGdydWJlci5uZXQiLCJzZXNzaW9uSWQiOiJlOWFkYWZjYi04NDc0LTRjY2QtYmFlYi01NGJiMzI5NWFlYTYifQ==
  # groundcoverPredefinedTokenSecret:
  #   # the name of the secret
  #   secretName: temp-groundcover-secret
  #   # the key in the secret containing the token value
  #   secretKey: GROUNDCOVER_KEY
clusterId: bomdemo-cluster

timescaledb-single:
  persistentVolumes:
    data:
      enabled: false
    wal:
      enabled: false

  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: password
      PATRONI_REPLICATION_PASSWORD: password
      PATRONI_admin_PASSWORD: password

loki:
  persistence:
    enabled: false

victoria-metrics-single:
  server:
    persistentVolume:
      enabled: false