controller:
  kind: DaemonSet
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      # AWS Load Balancer Controller Annotations
      service.beta.kubernetes.io/aws-load-balancer-type: external
    
    targetPorts:
      http: http
      https: https

