apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: external-dns
    server: 'https://kubernetes.default.svc'
  source:
    path: external-dns
    repoURL: 'https://github.com/BOM-DEMO/tools-deploy.git'
    targetRevision: HEAD
  project: bom-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true