helmChartInflationGenerator:
  - chartRepoUrl: https://charts.bitnami.com/bitnami
    chartName: external-dns
    releaseName: external-dns
    releaseNamespace: external-dns
    values: values.yaml

namespace: external-dns