helmChartInflationGenerator:
  - chartRepoUrl: https://charts.jetstack.io
    chartName: cert-manager
    releaseName: cert-manager
    releaseNamespace: cert-manager
    values: values.yaml

namespace: cert-manager